// wikipedia.de/ctrl/components/footer.svelte
<div class="banner__footer">
	<div class="footer">
		<div class="footer__item">
			<span>Spendenkonto Wikimedia Foerdergesellschaft</span>
		</div>
		<div class="footer__item">
			<span>BIC</span>
			<span class="footer__importantinfo">BFSWDE33BER</span>
		</div>
		<div class="footer__item">
			<span>IBAN</span>
			<span class="footer__importantinfo"><span class="iban-block"><span>DE33</span><span>1002</span><span>0500</span><span>0001</span><span>1947</span><span>00</span></span></span>
		</div>

		<div class="footer__item footer__item--rightflex">
			<a id="application-of-funds-link" class="application-of-funds-link" target="_blank"
			   href="https://spenden.wikimedia.de/use-of-funds?piwik_campaign={campaignName}&piwik_kwd={bannerName}_link&skin=0&dsn=0"
			   data-href="#info-application-of-funds">Wohin geht meine Spende?
			</a>
		</div>
	</div>
</div>

<script>
	export let campaignName;
	export let bannerName;
</script>

<style lang="postcss" global>
    @import "footer.pcss";
</style>

// wikipedia.de/components/Footer.jsx
import { h } from 'preact';
import style from './Footer.pcss';

export default function Footer( { campaignName, bannerName} ) {
	return <div className="banner__footer">
		<div className="footer">
			<div className="footer__item">
				<span>Spendenkonto Wikimedia Foerdergesellschaft</span>
			</div>
			<div className="footer__item">
				<span>BIC</span>
				<span className="footer__importantinfo">BFSWDE33BER</span>
			</div>
			<div className="footer__item">
				<span>IBAN</span>
				<span className="footer__importantinfo"><span
					className="iban-block"><span>DE33</span><span>1002</span><span>0500</span><span>0001</span><span>1947</span><span>00</span></span></span>
			</div>

			<div className="footer__item footer__item--rightflex">
				<a id="application-of-funds-link" className="application-of-funds-link" target="_blank"
				   href={'https://spenden.wikimedia.de/use-of-funds?piwik_campaign=' + campaignName + '&piwik_kwd=' + bannerName + '_link&skin=0&dsn=0'}
				   data-href="#info-application-of-funds">Wohin geht meine Spende?
				</a>
			</div>
		</div>
	</div>
}
