// wikipedia.de_prototype/banners/DesktopBanner.jsx
import { h } from 'preact';
import classNames from 'classnames';

import style from './DesktopBanner.pcss';
import DonationForm from '../components/DonationForm';
import Footer from '../components/Footer';
import Funds from '../components/Funds';
import Infobox from '../components/Infobox';

export default function DesktopBanner( props ) {
	return <div id="WMDE_Banner" className={classNames({'is-hidden': !props.bannerVisible})}>
		<div className="banner">
			<div className="banner__content">
				<div className="infobox">
					<Infobox amountBannerImpressionsInMillion={props.amountBannerImpressionsInMillion}
							 numberOfDonors={props.numberOfDonors}
							 campaignDaySentence={props.campaignDaySentence}
							 weekdayPrepPhrase={props.weekdayPrepPhrase}
							 currentDayName={props.currentDayName}/>
				</div>
				<DonationForm bannerName={props.bannerName} campaignName={props.campaignName} />
			</div>
			<div className="close">
				<button className="close__link" onClick={props.closeBanner}>&#x2715;</button>
			</div>
			<Footer bannerName={props.bannerName} campaignName={props.campaignName} />
		</div>
		<Funds/>
	</div>
}

// wikipedia.de_prototype/ctrl/banners/desktop_banner.svelte
<div id="WMDE_Banner" class:is-hidden={isHidden}>
	<div class="banner">
		<div class="banner__content">
			<div class="infobox">
				<Text	amountBannerImpressionsInMillion="{amountBannerImpressionsInMillion}"
						numberOfDonors="{numberOfDonors}"
						campaignDaySentence="{campaignDaySentence}"
						weekdayPrepPhrase="{weekdayPrepPhrase}"
						currentDayName="{currentDayName}"/>
				<ProgressBar progressBar="{progressBar}"/>
			</div>
			<Form campaignName="{campaignName}" bannerName={bannerName} />
		</div>
		<div class="close"><button class="close__link" on:click={closeBanner}>&#x2715;</button></div>
		<Footer campaignName="{campaignName}" bannerName={bannerName} />
	</div>
	<Funds/>
</div>

<script>
	import Text from '../components/text.svelte';
	import Form from '../components/form.svelte';
	import ProgressBar from '../components/progressbar.svelte';
	import Footer from '../components/footer.svelte';
	import Funds from '../components/funds.svelte';

	export let weekdayPrepPhrase;
	export let campaignDaySentence;
	export let currentDayName;
	export let campaignName;
	export let bannerName;
	export let amountBannerImpressionsInMillion;
	export let numberOfDonors;
	export let progressBar;
	export let isHidden = false;

	function closeBanner(  ) {
		isHidden = true;
	}
</script>

<style lang="postcss" global>
	@import 'desktop_banner.pcss';
</style>
