// wikipedia.de_old/banners/DesktopBanner.jsx
// eslint-disable-next-line no-unused-vars
import { h, Component } from 'preact';
import classNames from 'classnames';

import DonationForm from '../components/DonationForm';
import Footer from '../components/Footer';
import Infobox from '../components/Infobox';
import ProgressBar from '../components/ProgressBar';
import FundsModal from '../../shared/components/ui/FundsModal';

export default class DesktopBanner extends Component {

	constructor( props ) {
		super( props );
		this.state = {
			isFundsModalVisible: false
		};
	}

	componentDidMount() {
		if ( this.startAnimation ) {
			this.startAnimation();
		}
	}

	setStartAnimation = ( startAnimation ) => {
		this.startAnimation = startAnimation;
	};

	setToggleFundsModal = () => {
		this.props.trackingData.eventTracker.trackEvent( 'application-of-funds-shown', this.props.trackingData.bannerClickTrackRatio );
		this.setState( { isFundsModalVisible: !this.state.isFundsModalVisible } );
	};

	render( props ) {
		const campaignProjection = props.campaignProjection;
		return <div id="WMDE_Banner" className={classNames( { 'is-hidden': !props.bannerVisible } )}>
			<div className="banner banner--desktop">
				<div className="banner__content">
					<div className="infobox">
						<Infobox amountBannerImpressionsInMillion={props.amountBannerImpressionsInMillion}
							numberOfDonors={props.numberOfDonors}
							campaignDaySentence={props.campaignDaySentence}
							weekdayPrepPhrase={props.weekdayPrepPhrase}
							currentDayName={props.currentDayName}/>
						<ProgressBar
							locale={props.locale}
							daysLeft={campaignProjection.getRemainingDays()}
							donationAmount={campaignProjection.getProjectedDonationSum()}
							goalDonationSum={campaignProjection.goalDonationSum}
							missingAmount={campaignProjection.getProjectedRemainingDonationSum()}
							setStartAnimation={this.setStartAnimation}/>
					</div>
					<DonationForm bannerName={props.bannerName} campaignName={props.campaignName}/>
				</div>
				<div className="close">
					<button className="close__link" onClick={props.closeBanner}>&#x2715;</button>
				</div>
				<Footer setToggleFundsModal={this.setToggleFundsModal}/>
			</div>
			<FundsModal fundsModalData={props.fundsModalData}
				setToggleFundsModal={this.setToggleFundsModal}
				isFundsModalVisible={ this.state.isFundsModalVisible }
				locale={ props.locale }/>
		</div>;
	}
}

// wikipedia.de_prototype/ctrl/banners/desktop_banner.svelte
<div id="WMDE_Banner" class:is-hidden={ ( isHidden || $isClosed ) }>
	<div class="banner">
		<div class="banner__content">
			<div class="infobox">
				<Text	amountBannerImpressionsInMillion="{amountBannerImpressionsInMillion}"
						numberOfDonors="{numberOfDonors}"
						campaignDaySentence="{campaignDaySentence}"
						weekdayPrepPhrase="{weekdayPrepPhrase}"
						currentDayName="{currentDayName}"/>
				<ProgressBar progressBar="{progressBar}"/>
			</div>
			<Form campaignName="{campaignName}" bannerName={bannerName} />
		</div>
		<div class="close"><button class="close__link" on:click={closeBanner}>&#x2715;</button></div>
		<Footer campaignName="{campaignName}" bannerName={bannerName} />
	</div>
	<Funds/>
</div>

<script>
	import Text from '../components/text.svelte';
	import Form from '../components/form.svelte';
	import ProgressBar from '../components/progressbar.svelte';
	import Footer from '../components/footer.svelte';
	import Funds from '../components/funds.svelte';
	// eslint-disable-next-line no-unused
	import { isClosed } from '../stores.js';

	export let weekdayPrepPhrase;
	export let campaignDaySentence;
	export let currentDayName;
	export let campaignName;
	export let bannerName;
	export let amountBannerImpressionsInMillion;
	export let numberOfDonors;
	export let progressBar;
	export let isHidden = false;
	export let trackingData;

	function closeBanner() {
		trackingData.eventTracker.trackEvent( 'banner-closed', trackingData.bannerCloseTrackRatio );
		isHidden = true;
		$isClosed = true;
	}
</script>

<style lang="postcss" global>
	@import 'desktop_banner.pcss';
</style>
