// wikipedia.de_prototype/ctrl/banners/mobile_banner.svelte
<div class="mini-banner">
	<div class="mini-banner-box">
		<div class="mini-banner-content">
			<div class="mini-banner-headline">
				<div>
					<span>Die Wikimedia-Spendenkampagne</span>
				</div>
			</div>
			<div id="mini-banner-close-button" class="mini-banner-close-button"></div>
			<div class="mini-banner-carousel">
				<div class="carousel-cell">
					<p>Liebe Leserinnen und Leser, an diesem { currentDayName } sind Sie in Deutschland gefragt:</p>
				</div>
				<div class="carousel-cell">
					<p>Über { amountBannerImpressionsInMillion } Millionen Mal wird unser Spendenaufruf täglich angezeigt, aber nur { numberOfDonors } Menschen haben bisher gespendet. Schon der Preis einer Tasse Kaffee würde genügen.</p>
				</div>
				<div class="carousel-cell">
					<p class="goal-headline">Unser Spendenziel: 8,1&nbsp;Millionen&nbsp;Euro</p>
					{@html progressBar }
				</div>
				<div class="carousel-cell">
					<p>Wenn alle, die das jetzt lesen, einen kleinen Beitrag leisten, wäre unser Spendenziel bereits am heutigen { currentDayName } erreicht.</p>
				</div>
				<div class="carousel-cell">
					<p>Es ist leicht, diese Nachricht zu ignorieren und die meisten werden das wohl tun.</p>
				</div>
				<div class="carousel-cell">
					<p>Wenn Sie Wikipedia nützlich finden, nehmen Sie sich an diesem { currentDayName } bitte eine Minute Zeit und geben Wikipedia mit Ihrer Spende etwas zurück.</p>
				</div>
			</div>
			<div class="mini-banner-tab">
				<div class="mini-banner-tab-inner" on:click={showForm}>
					Jetzt spenden
				</div>
			</div>
		</div>
	</div>
</div>

<MobileFullPageBanner
		weekdayPrepPhrase="{weekdayPrepPhrase}"
		campaignDaySentence="{campaignDaySentence}"
		currentDayName="{currentDayName}"
		campaignName="{campaignName}"
		bannerName="{bannerName}"
		amountBannerImpressionsInMillion="{amountBannerImpressionsInMillion}"
		numberOfDonors="{numberOfDonors}"
		progressBar="{progressBar}"/>

<script>
	import { Slider } from '../../../shared/banner_slider';
	import { onMount } from 'svelte';
	import MobileFullPageBanner from './mobile_banner_fullpage.svelte';

	export let weekdayPrepPhrase;
	export let campaignDaySentence;
	export let currentDayName;
	export let campaignName;
	export let bannerName;
	export let amountBannerImpressionsInMillion;
	export let numberOfDonors;
	export let progressBar;

	const sliderAutoPlaySpeed = 5000;
	const fullscreenBannerSlideInSpeed = 1250;

	/**
	 * Slider wrapper object holding a Flickity-based slider
	 * @type {Slider}
	 */
	const bannerSlider = new Slider( sliderAutoPlaySpeed );

	onMount(async () => {
		bannerSlider.initialize();
		bannerSlider.enableAutoplay();
	});

	function showForm(  ) {
		alert('TODO');
	}
</script>

<style lang="postcss" global>
	@import 'mobile_banner.pcss';
</style>

// wikipedia.de_prototype/banners/MobileBanner.jsx
import { Component, Fragment, h } from 'preact';
import style from './MobileBanner.pcss';
import { Slider } from '../../mobile/banner_slider';

export default class MobileBanner extends Component {

	componentDidMount() {
		this.bannerSlider = new Slider( this.props.sliderAutoPlaySpeed );
		this.bannerSlider.initialize();
		this.bannerSlider.enableAutoplay();
	}

	showForm = e => {
		console.log("TODO: Show form");
	};

	render( props, state, context ) {
		return <Fragment>
			<div className="mini-banner">
				<div className="mini-banner-box">
					<div className="mini-banner-content">
						<div className="mini-banner-headline">
							<div>
								<span>Die Wikimedia-Spendenkampagne</span>
							</div>
						</div>
						<div id="mini-banner-close-button" className="mini-banner-close-button"
							 onclick={props.closeBanner}></div>
						<div className="mini-banner-carousel">
							<div className="carousel-cell">
								<p>Liebe Leserinnen und Leser, an diesem {props.currentDayName} sind Sie in Deutschland
									gefragt:</p>
							</div>
							<div className="carousel-cell">
								<p>Über {props.amountBannerImpressionsInMillion} Millionen Mal wird unser Spendenaufruf
									täglich angezeigt, aber nur {props.numberOfDonors} Menschen haben bisher gespendet. Schon
									der Preis einer Tasse Kaffee würde genügen.</p>
							</div>
							<div className="carousel-cell">
								<p className="goal-headline">Unser Spendenziel: 8,1&nbsp;Millionen&nbsp;Euro</p>
							</div>
							<div className="carousel-cell">
								<p>Wenn alle, die das jetzt lesen, einen kleinen Beitrag leisten, wäre unser Spendenziel
									bereits am heutigen {props.currentDayName} erreicht.</p>
							</div>
							<div className="carousel-cell">
								<p>Es ist leicht, diese Nachricht zu ignorieren und die meisten werden das wohl tun.</p>
							</div>
							<div className="carousel-cell">
								<p>Wenn Sie Wikipedia nützlich finden, nehmen Sie sich an diesem {props.currentDayName} bitte
									eine Minute Zeit und geben Wikipedia mit Ihrer Spende etwas zurück.</p>
							</div>
						</div>
						<div className="mini-banner-tab">
							<div className="mini-banner-tab-inner" onClick={this.showForm}>
								Jetzt spenden
							</div>
						</div>
					</div>
				</div>
			</div>
		</Fragment>
	}

}
